# This is a basic workflow to help you get started with Actions

name: Special Work FLow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    if: contains(github.event.head_commit.message, 'Bump and Publish')
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Branch
        uses: actions/checkout@v2


      # Runs a single command using the runners shell
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.7

      # Runs a set of commands using the runners shell
      - name: Bump Version
        run: 
          python auto-increment.py
          
      - name: Commit Bumped Version
        run: |
          git config --global user.name 'Tanmoy Sen Gupta'
          git config --global user.email 'tanmoysg@users.noreply.github.com'
          git commit -am "Bumped Version Up"
          git push
  
#   test:
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Echo Message
#       - run:
#           echo "Bumped and Published"
